### ISSUE TITLE
WebAuthnAuthenticatorManager and persistent storage

### ISSUE THREAD

**Issue by blacelle** [webauthn4j/webauthn4j-spring-security#1108]
Is there any recommendation regarding WebAuthnAuthenticatorManager storage (e.g. in JDBC?).

It would very helpful if the projects provide a default (or sample) implementation (e.g. in JDBC).

**Comment by ynojima** [comment]
Since its design varies by use-cases, we couldn't provide a default implementation, but instead, we provides a sample implementation with JPA:
https://github.com/webauthn4j/webauthn4j-spring-security/blob/master/samples/spa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/domain/component/AuthenticatorManagerImpl.java
https://github.com/webauthn4j/webauthn4j-spring-security/blob/master/samples/spa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/domain/repository/AuthenticatorEntityRepository.java
