### ISSUE TITLE
Is origin validation spec conform in its current form?

### ISSUE THREAD

**Issue by nojomyth-dev** [webauthn4j/webauthn4j-spring-security#1347]
Hi,

currently, the origin validation in OriginValidatorImpl uses the exact request URL (http(s)://server:port) for the validation of the origin. 
I thought according to the specs (WebAuthn level 2), the validation of the origin should happen based on the RP ID, thus also allowing subdomains (e.g. for the rpId example.com, test.example.com would be allowed). Therefore, the protocol should not be matched, neither the port.
Furthermore, only https should be permissible.
How might one change this behavior without reimplementation in their code base? Currently i just provide another ServerPropertiesProvider with the "correct" URL

Is it possible to use reverse proxying with the current approach without having to reimplement the default behavior in my project?

Thanks

**Comment by ynojima** [comment]
It sounds you are mixing up `rpId` and `origin`.
`rpId`, which is a scope for the credential, can be relaxed to the registrable domain suffix. Port and scheme are not part of rpId.
To validate `rpId`, `RpIdHashValidator` is used, Not `OriginValidatorImpl`.
https://github.com/webauthn4j/webauthn4j/blob/master/webauthn4j-core/src/main/java/com/webauthn4j/validator/RpIdHashValidator.java

`origin` is used for phishing attack prevension. `origin` value is supplied from the browser while creating the WebAuthn attestation and assertion, and the RP need to check exact matching with the URL the RP is serving the contents.

If you really want to allow multiple origins, you may supply multiple origins to the `ServerProperty` constructor from your `ServerPropertyProvider` implementation.

> Furthermore, only https should be permissible.

More precisely, WebAuthn API is allowed only to secure contexts, and secure contexts contains localhost with http.
https://www.w3.org/TR/webauthn/#sctn-api
Since secure context check is implemented in the browser, and the check is not required for the RP implementation by the FIDO conformance test, it is not implemented in WebAuthn4J.

**Comment by nojomyth-dev** [comment]
Thanks, i got things mixed up!
